// src/App.jsx
import { useState, useEffect } from 'react';
import './App.scss';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { useTranslation } from 'react-i18next';
import Repository from './repositories/RepositoryFactory';
import liquidParser from './liquid/liquidParser';

import ExampleComponent from './components/ExampleComponent/component.jsx';

const PostRepository = Repository.get('posts');

function App() {
  const {t} = useTranslation();
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState();
  const year = 2020;
  const siteName = liquidParser.parse('{{site.name}}');
  const getPosts = async () => {
    setLoading(true);
    try {
      const response = await PostRepository.getTop(3);
      const postsResponse = response.entries.map((entry) => ({
        description: entry.fields.description,
        id: entry.meta.uuid,
        title: entry.fields.title,
        slug: entry.fields.slug,
        image: entry.fields.covers ? entry.fields.covers[0].url : '',
        imageAlt: entry.fields.covers ? entry.fields.covers[0].alt_text : '',
      }));
      setPosts(postsResponse);
      return postsResponse;
    } catch (error) {
      return error;
    } finally {
      setLoading(false);
    }
  };
  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div className="test-app">
      <div className="pt-5">
        <div className="container">
          <div className="row">
            <div className="col-md-2" />
            <div className="col-md-8 text-center">
              <h1 className="mb-3">
                {t('title')}
              </h1>
              <h2 className="h4 mb-4">
                Welcome to the Minimal theme.
                This is an HTML widget that you can modify in the Page Builder section.
                You can also modify the style in the Template Builder section.
              </h2>
              <a
                className="btn btn-primary btn-lg"
                href="https://www.modyo.com"
              >
                Go to Modyo
              </a>
              <a
                className="btn btn-outline-primary ml-2 btn-lg"
                href="https://docs.modyo.com"
              >
                Read the docs
              </a>
            </div>
          </div>
          <div className="mt-2">
            <img
              src="https://cloud.modyocdn.com/uploads/2addb891-7316-4cfb-882a-f0fd9745bf3a/original/homeMinimal.png"
              alt="modyo"
            />
          </div>
        </div>
      </div>
      <div className="bg-light py-5">
        <div className="container py-5">
          <div className="row">
            <div className="col-md-2" />
            <div className="col-md-8 text-center">
              <h2 className="mb-3">
                Create and launch digital products faster
              </h2>
              <p className="text-muted mb-4">
                Welcome to the Minimal theme.
                This is an HTML widget that you can modify in the Page Builder section.
                You can also modify the style in the Template Builder section.
              </p>
              <div className="px-5 my-5">
                <img
                  className="w-50"
                  src="https://cloud.modyocdn.com/uploads/8ab8adac-898d-4c38-a878-8788a4b3df0f/original/diseno.png"
                  alt="modyo"
                />
              </div>
              <a
                className="btn btn-outline-primary"
                href="http://www.modyo.com"
              >
                Learn more
              </a>
            </div>
          </div>
        </div>
      </div>
      <div className="bg-white py-5">
        <div className="container py-5">
          <div className="row">
            <div className="col-md-2" />
            <div className="col-md-8 text-center">
              <div className="row">
                {
                  posts.map((post) => (
                    <ExampleComponent key={post.id} loading={loading} post={post} />
                  ))
                }
              </div>
            </div>
          </div>
        </div>
        <div
          id="footer"
          className="py-5 mt-4"
          role="contentinfo"
        >
          <div className="container">
            <div className="mt-2 pt-2 border-top d-flex">
              <span>
                { siteName }
                {' '}
                &copy;
                { year }
              </span>

              <span className="ml-auto">
                Made with
                <FontAwesomeIcon
                  icon="heart"
                  color="red"
                  className="mx-2"
                />
                in
                {' '}
                <a href="https://www.modyo.com">Modyo CLI</a>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;

// src/App.vue
<template>
  <div id="app">
    <div class="pt-5">
      <div class="container">
        <div class="row">
          <div class="col-md-2" />
          <div class="col-md-8 text-center">
            <h1 class="mb-3">
              Build better digital products to unify your customer experiences and accelerate growth.
            </h1>
            <h2 class="h4 mb-4">
              Welcome to the Minimal theme.
              This is an HTML widget that you can modify in the Page Builder section.
              You can also modify the style in the Template Builder section.
            </h2>
            <a
              class="btn btn-primary btn-lg"
              href="https://www.modyo.com">Go to Modyo</a>
            <a
              class="btn btn-outline-primary ml-2 btn-lg"
              href="https://docs.modyo.com">Read the docs</a>
          </div>
        </div>
        <div class="mt-2">
          <img
            src="https://cloud.modyocdn.com/uploads/2addb891-7316-4cfb-882a-f0fd9745bf3a/original/homeMinimal.png"
            alt="modyo">
        </div>
      </div>
    </div>
    <div class="bg-light py-5">
      <div class="container py-5">
        <div class="row">
          <div class="col-md-2" />
          <div class="col-md-8 text-center">
            <h2 class="mb-3">
              Create and launch digital products faster
            </h2>
            <p class="text-muted mb-4">
              Welcome to the Minimal theme.
              This is an HTML widget that you can modify in the Page Builder section.
              You can also modify the style in the Template Builder section.
            </p>
            <div class="px-5 my-5">
              <img
                class="w-50"
                src="https://cloud.modyocdn.com/uploads/8ab8adac-898d-4c38-a878-8788a4b3df0f/original/diseno.png"
                alt="modyo">
            </div>
            <a
              class="btn btn-outline-primary"
              href="http://www.modyo.com">Learn more</a>
          </div>
        </div>
      </div>
    </div>
    <div class="bg-white py-5">
      <div class="container py-5">
        <div class="row">
          <div class="col-md-2" />
          <div class="col-md-8 text-center">
            <div class="row">
              <post-card
                v-for="post in allPosts"
                :key="post.id"
                v-bind="post" />
            </div>
          </div>
        </div>
      </div>
    </div>
    <div
      id="footer"
      class="py-5 mt-4"
      role="contentinfo">
      <div class="container">
        <div class="mt-2 pt-2 border-top d-flex">
          <span>{{ siteName }} &copy;{{ year }}</span>
          <span class="ml-auto">Made with <font-awesome-icon
            :icon="['fas', 'heart']"
            color="red"
            class="mx-2" /> in <a href="https://www.modyo.com">Modyo CLI</a></span>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import PostCard from './components/PostCard.vue';
import Repository from './repositories/RepositoryFactory';

const PostRepository = Repository.get('posts');
export default {
  name: 'App',
  components: {
    PostCard,
  },
  data() {
    return {
      year: new Date().getFullYear(),
      siteName: 'My Site',
      allPosts: [],
    };
  },
  async created() {
    const allPosts = await PostRepository.all();
    this.allPosts = allPosts.entries.map((post) => ({
      id: post.meta.uuid,
      title: post.meta.name,
      updatedAt: new Date(post.meta.updated_at),
      publishedAt: new Date(post.meta.published_at),
      description: post.fields.Details,
      excerpt: post.fields.Excerpt,
      image: post.fields.Featured.url,
      url: post.fields.Link,
    }));
  },
};
</script>

<style lang="scss">
img {
  max-width: 100%;
}
</style>
